### ISSUE TITLE
raspberry build fails

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/freedom-maker#107]
The build for raspberry (RPi1) is consistently failing for me:
```
Errors were encountered while processing:
 /tmp//apt-dpkg-install-sUML3S/002-python3-django_1%3a1.10.7-2_all.deb
 /tmp//apt-dpkg-install-sUML3S/124-locales-all_2.24-11+deb9u1_armel.deb
E: Sub-process /var/tmp/dpkg-eatmydata returned an error code (1)
```

**Comment by lucafavatella** [comment]
@jvalleroy I attempted to reproduce your error building the raspberry target but I did not manage to. Could you please share more details of your setup? Please find below the attempts I made: on Travis CI, and on OSX laptop.

----

Somehow on Docker in Travis CI I do not observe this - see #111 

----

Somehow on Docker on Docker Machine (Virtualbox driver) in my local OSX laptop I observe an error attempting to build the raspberry target.

It looks like that `apt-get` in plain `chroot` command does not see the network. It looks an error [related to network/DNS configuration in the chroot e.g. resolv.conf](https://askubuntu.com/questions/590354/after-chroot-apt-get-update-err-and-failed-to-fetch-bootableflashfromharddis/590358#590358) but it is not clear to me why I do not experience this error in Travis CI. The error I see is the following:
```
...
2017-07-22 21:28:28,767 - INFO - Executing command - (['taskset', '0x01', 'sudo', '-H', 'MACHINE=raspberry', 'MIRROR=http://deb.debian.org/debian', 'BUILD_MIRROR=http://deb.debian
.org/debian', 'SOURCE=false', 'SOURCE_IN_IMAGE=false', 'SUITE=stable', 'ENABLE_NONFREE=yes', 'vmdebootstrap', '--hostname', 'freedombox', '--image', 'build/freedombox-stable-nonfr
ee_2017-07-22_raspberry-armel.img.temp', '--size', '3800M', '--mirror', 'http://deb.debian.org/debian', '--distribution', 'stable', '--arch', 'armel', '--lock-root-password', '--l
og', 'build/freedombox-stable-nonfree_2017-07-22_raspberry-armel.log', '--log-level', 'debug', '--verbose', '--customize', '/tmp/tmp.stW83tutcG/freedom-maker/freedommaker/freedomb
ox-customize', '--foreign', '/usr/bin/qemu-arm-static', '--no-extlinux', '--bootsize', '128M', '--no-kernel', '--roottype', 'ext4', '--boottype', 'vfat', '--package', 'initramfs-t
ools'],)
+ set -o pipefail
+ use_eatmydata=true
+ rootdir=/tmp/tmpLNYb8V
+++ dirname build/freedombox-stable-nonfree_2017-07-22_raspberry-armel.img.temp
++ cd build
++ pwd
++ basename build/freedombox-stable-nonfree_2017-07-22_raspberry-armel.img.temp
+ image=/tmp/tmp.stW83tutcG/freedom-maker/build/freedombox-stable-nonfree_2017-07-22_raspberry-armel.img.temp
+ case "$MACHINE" in
+ mount_file_systems
+ mount /dev -t devfs -o bind /tmp/tmpLNYb8V/dev
+ mount /dev/pts -t devpts -o bind /tmp/tmpLNYb8V/dev/pts
+ mount /proc -t proc -o bind /tmp/tmpLNYb8V/proc
+ mount /sys -t sys -o bind /tmp/tmpLNYb8V/sys
+ trap unmount_file_systems EXIT
+ cd /tmp/tmpLNYb8V
+ echo info: building raspberry
info: building raspberry
+ export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
+ DEBIAN_FRONTEND=noninteractive
+ DEBCONF_NONINTERACTIVE_SEEN=true
+ export LC_ALL=C LANGUAGE=C LANG=C
+ LC_ALL=C
+ LANGUAGE=C
+ LANG=C
+ export TMP=/tmp/ TMPDIR=/tmp/
+ TMP=/tmp/
+ TMPDIR=/tmp/
+ username=fbx
+ echo 'info: creating initial user fbx with disabled password!'
info: creating initial user fbx with disabled password!
+ chroot /tmp/tmpLNYb8V adduser --gecos fbx --disabled-password fbx
Adding user `fbx' ...
Adding new group `fbx' (1000) ...
Adding new user `fbx' (1000) with group `fbx' ...
Creating home directory `/home/fbx' ...
Copying files from `/etc/skel' ...
+ chroot /tmp/tmpLNYb8V adduser fbx sudo
Adding user `fbx' to group `sudo' ...
Adding user fbx to group sudo
Done.
+ case "$MACHINE" in
+ set_apt_sources http://deb.debian.org/debian
+ NEW_MIRROR=http://deb.debian.org/debian
+ COMPONENTS=main
+ '[' yes = yes ']'
+ COMPONENTS='main contrib non-free'
+ cat
+ '[' stable '!=' unstable ']'
+ '[' stable '!=' sid ']'
+ cat
+ chroot /tmp/tmpLNYb8V apt-get update
Err:1 http://security.debian.org stable/updates InRelease
  Temporary failure resolving 'security.debian.org'
Err:2 http://deb.debian.org/debian stable InRelease
  Temporary failure resolving 'deb.debian.org'
Err:3 http://deb.debian.org/debian stable-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists... Done
W: Failed to fetch http://deb.debian.org/debian/dists/stable/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/dists/stable/updates/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/stable-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
+ cat
+ chmod a+rx /tmp/tmpLNYb8V/usr/sbin/policy-rc.d
+ true
+ enable_eatmydata_override
+ chroot /tmp/tmpLNYb8V apt-get install --no-install-recommends -y eatmydata
Reading package lists... Done
Building dependency tree... Done
The following additional packages will be installed:
  libeatmydata1
The following NEW packages will be installed:
  eatmydata libeatmydata1
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 29.6 kB of archives.
After this operation, 62.5 kB of additional disk space will be used.
Err:1 http://deb.debian.org/debian stable/main armel libeatmydata1 armel 105-5
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/debian stable/main armel eatmydata all 105-5
  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/libe/libeatmydata/libeatmydata1_105-5_armel.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/libe/libeatmydata/eatmydata_105-5_all.deb  Temporary failure resolving 'deb.debian.org'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
+ unmount_file_systems
+ umount /tmp/tmpLNYb8V/dev/pts
+ umount /tmp/tmpLNYb8V/dev
+ umount /tmp/tmpLNYb8V/proc
+ umount /tmp/tmpLNYb8V/sys
+ case "$MACHINE" in
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/tmp.stW83tutcG/freedom-maker/freedommaker/__main__.py", line 30, in <module>
    Application().run()
  File "/tmp/tmp.stW83tutcG/freedom-maker/freedommaker/application.py", line 74, in run
    builder.build()
  File "/tmp/tmp.stW83tutcG/freedom-maker/freedommaker/builder.py", line 102, in build
    self.make_image()
  File "/tmp/tmp.stW83tutcG/freedom-maker/freedommaker/builder.py", line 160, in make_image
    self._run(command)
  File "/tmp/tmp.stW83tutcG/freedom-maker/freedommaker/builder.py", line 300, in _run
    stderr=file_handle, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['taskset', '0x01', 'sudo', '-H', 'MACHINE=raspberry', 'MIRROR=http://deb.debian.org/debian', 'BUILD_MIRROR=http://deb.debian.org/debian',
'SOURCE=false', 'SOURCE_IN_IMAGE=false', 'SUITE=stable', 'ENABLE_NONFREE=yes', 'vmdebootstrap', '--hostname', 'freedombox', '--image', 'build/freedombox-stable-nonfree_2017-07-22_
raspberry-armel.img.temp', '--size', '3800M', '--mirror', 'http://deb.debian.org/debian', '--distribution', 'stable', '--arch', 'armel', '--lock-root-password', '--log', 'build/fr
eedombox-stable-nonfree_2017-07-22_raspberry-armel.log', '--log-level', 'debug', '--verbose', '--customize', '/tmp/tmp.stW83tutcG/freedom-maker/freedommaker/freedombox-customize',
 '--foreign', '/usr/bin/qemu-arm-static', '--no-extlinux', '--bootsize', '128M', '--no-kernel', '--roottype', 'ext4', '--boottype', 'vfat', '--package', 'initramfs-tools']' return
ed non-zero exit status 1
```

The script I used is:
```sh
#!/bin/bash

REPO=https://github.com/freedombox/freedom-maker.git
COMMIT=78953a0

BUILD_DISTRIBUTION=stretch
COMMON_DEPS="python3-minimal libpython3-stdlib sudo vmdebootstrap"
DISTRIBUTION=stable

TARGET=raspberry
TARGET_DEPS="dosfstools qemu-user-static binfmt-support pxz"

CONTAINER_NAME=freedom-maker-build-host

docker run \
       -it \
       --name "${CONTAINER_NAME:?}" \
       --privileged \
       debian:"${BUILD_DISTRIBUTION:?}" \
       /bin/sh -c "
{ set -e
  apt-get -qq update
  apt-get install -y --no-install-recommends ca-certificates git
  apt-get install -y --no-install-recommends ${COMMON_DEPS:?}
  apt-get install -y --no-install-recommends ${TARGET_DEPS:?}
  WorkDir=\$(mktemp -d)
  cd \"\${WorkDir:?}\"
  git clone \"${REPO:?}\" freedom-maker
  cd freedom-maker
  git checkout \"${COMMIT:?}\"
  python3 -m freedommaker \"${TARGET:?}\" --distribution=\"${DISTRIBUTION:?}\"
  ls -l build
  file build/freedombox-*.img*
  Img=\"\$(ls build/freedombox-*.img* | head -n 1)\"
} >&2
cat \"\${Img:?}\" | openssl base64
{ echo \"HINT openssl base64 -d > \$(basename \${Img:?})\" } >&2
"
```

**Comment by lucafavatella** [comment]
I noticed that `freedombox-customize` runs `dpkg` and `apt-get` by chroot for installing packages: I am not sure why `builder` does not use `vmdebootstrap` options [`package`](http://git.liw.fi/vmdebootstrap/tree/bin/vmdebootstrap?h=vmdebootstrap-1.7#n100) (instead of `apt-get`) and [`custom-package`](http://git.liw.fi/vmdebootstrap/tree/bin/vmdebootstrap?h=vmdebootstrap-1.7#n101) (instead of `dpkg`).
```
$ git grep "chroot.*\(dpkg\|apt\)" 78953a0
78953a0:freedommaker/freedombox-customize:21:    chroot $rootdir apt-get install --no-install-recommends -y eatmydata
78953a0:freedommaker/freedombox-customize:86:        chroot "$rootdir" dpkg -i "$firmware_tempfile"
78953a0:freedommaker/freedombox-customize:187:chroot $rootdir apt-get update
78953a0:freedommaker/freedombox-customize:201:    chroot "$rootdir" apt-get install -y gdebi-core
78953a0:freedommaker/freedombox-customize:207:    chroot "$rootdir" apt-get install -y gdebi-core
78953a0:freedommaker/freedombox-customize:210:    chroot "$rootdir" apt-get install -y freedombox-setup
78953a0:freedommaker/freedombox-customize:285:chroot $rootdir apt-get update
```

**Comment by lucafavatella** [comment]
> It looks like that apt-get in plain chroot command does not see the network. It looks an error related to network/DNS configuration in the chroot e.g. resolv.conf but it is not clear to me why I do not experience this error in Travis CI.
> ...
> I noticed that freedombox-customize runs dpkg and apt-get by chroot for installing packages: I am not sure why builder does not use vmdebootstrap options package (instead of apt-get) and custom-package (instead of dpkg).

I see that `freedombox-customize` is passed as the [vmdebootstrap option](http://git.liw.fi/vmdebootstrap/tree/bin/vmdebootstrap?h=vmdebootstrap-1.7#n110) and that it appears to be [called after network configuration](http://git.liw.fi/vmdebootstrap/tree/bin/vmdebootstrap?h=vmdebootstrap-1.7#n331).

I noticed that examples of customize scripts in vmdebootstrap repo e.g. [this](http://git.liw.fi/vmdebootstrap/tree/examples/beagleboneblack-customise.sh?h=vmdebootstrap-1.7) are simpler than `freedombox-customize` e.g. do not use `chroot` or install packages.

**Comment by jvalleroy** [comment]
I'm trying to build unstable images now:
- I don't see this issue for raspberry. Instead, it fails due to DNS error when trying to fetch the firmware.
- I am seeing this issue now for raspberry2.
- Same result on my laptop and desktop.

So I think this issue happening depends on the current state of the Debian release that you are building.
